services:
  - type: web
    name: laravel-app
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""      # Laravel dùng Apache nên không cần
    startCommand: ""      # Apache sẽ tự chạy
    autoDeploy: true

    envVars:
      # App
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false        # Nhớ chạy `php artisan key:generate` trước
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://webnc-th4.onrender.com
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_TIMEZONE
        value: Asia/Ho_Chi_Minh

      # Log
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug

      # Database
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-wnc-myqsl-wnc.l.aivencloud.com
      - key: DB_PORT
        value: "17592"
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false

      # Session
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"

      # Queue / Cache
      - key: QUEUE_CONNECTION
        value: sync         # Dùng `sync` nếu chưa setup queue
      - key: CACHE_DRIVER
        value: file         # Tốt hơn `database` nếu chưa setup bảng

      # Redis (bỏ nếu không dùng)
      - key: REDIS_CLIENT
        value: php
      - key: REDIS_HOST
        value: 127.0.0.1
      - key: REDIS_PORT
        value: "6379"

      # Mail
      - key: MAIL_MAILER
        value: log
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: Laravel

      # Vite (nếu có frontend Vite riêng)
      - key: VITE_APP_NAME
        value: Laravel
